######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 6 01:45:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clientmodel.h clientpresenter.h defandpar.h iviewform.h mainform.h
SOURCES += clientmodel.cpp clientpresenter.cpp main.cpp mianform.cpp
