######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 2 04:48:23 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt debug warn_on

# Input
HEADERS += mainform.h
SOURCES += main.cpp mianform.cpp
